// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Projet4_prog.Migrations
{
    [DbContext(typeof(Projet4_progContext))]
    [Migration("20260423141430_creationmodeleproduit")]
    partial class creationmodeleproduit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projet4_prog.Data.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbProduitRestant")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Prix")
                        .HasColumnType("float");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "bacon infusé au sirop d'érable cuisiner avec l'amour pour Jad",
                            NbProduitRestant = 67,
                            Nom = "Bacon halal au sirop d'érable",
                            Prix = 12.67,
                            image = "https://www.instagram.com/reel/DPHjzjGEixS/"
                        },
                        new
                        {
                            Id = 2,
                            Description = "c'est tellement bon pour mathis",
                            NbProduitRestant = 1,
                            Nom = "Pudding chomeur",
                            Prix = 16.670000000000002,
                            image = "https://www.allrecipes.com/recipe/267358/pouding-chomeur/"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Le sirop d'érable chauffé est versé dans la neige pour créer la tire. · Versez le sirop d'érable dans une neige compactée",
                            NbProduitRestant = 80,
                            Nom = "Tire d'érable",
                            Prix = 1.6699999999999999,
                            image = "https://www.noovomoi.ca/cuisiner/trucs-et-inspirations/article.etapes-tire-erable-maison.1.618708.html"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Des pitas mais sucrée",
                            NbProduitRestant = 8,
                            Nom = "3 Crèpes",
                            Prix = 8.6699999999999999,
                            image = "https://www.noovomoi.ca/cuisiner/trucs-et-inspirations/article.etapes-tire-erable-maison.1.618708.html"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
